# Generated by Django 4.1.7 on 2023-10-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0003_alter_userregistrationform_face_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationform',
            name='face_data',
            field=models.BinaryField(),
        ),
    ]
