# Generated by Django 4.1.7 on 2023-10-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0005_alter_userregistrationform_face_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistrationform',
            name='face_data',
        ),
    ]
