# Generated by Django 4.1.7 on 2023-10-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0006_remove_userregistrationform_face_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
                ('image1', models.CharField(max_length=200)),
                ('price1', models.CharField(max_length=200)),
                ('name_id', models.SmallIntegerField(max_length=200)),
            ],
        ),
    ]
