# Generated by Django 4.1.7 on 2023-10-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0007_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=100)),
                ('card_num', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=100)),
                ('ba_name', models.CharField(max_length=100)),
                ('p_pin', models.CharField(max_length=100)),
                ('m_num', models.CharField(max_length=100)),
                ('de_date', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('image2', models.CharField(max_length=200)),
                ('price2', models.CharField(max_length=200)),
            ],
        ),
    ]
