# Generated by Django 4.1.7 on 2023-10-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0008_add_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_chart',
            name='b_id',
            field=models.SmallIntegerField(max_length=200, null=True),
        ),
    ]
